module.exports = () => {
  return {
    categories: ["Watersports", "Soccer", "Chess", "baseball"],
    products: [
      {
        id: 1,
        name: "카약",
        category: "Watersports",
        description: "보트에는 한명만 들어갈수 있습니다",
        price: 275,
      },
      {
        id: 2,
        name: "라이프 자켓",
        category: "Watersports",
        description: "보호와 동시에 패션을!",
        price: 48.95,
      },
      {
        id: 3,
        name: "축구공",
        category: "Soccer",
        description: "피파 공식 사이즈의 축구공",
        price: 19.5,
      },
      {
        id: 4,
        name: "코너킥 깃발",
        category: "Soccer",
        description: "운동장을 좀더 정식경기장 처럼!",
        price: 34.95,
      },
      {
        id: 5,
        name: "스타디움",
        category: "Soccer",
        description: "35000석의 스타디움",
        price: 79500,
      },
      {
        id: 6,
        name: "띵킹컵",
        category: "Chess",
        description: "75퍼센트까지 두뇌의 효율성을 향상키자!",
        price: 16,
      },
      {
        id: 7,
        name: "불안정한 의자",
        category: "Chess",
        description: "상대방 몰래 설치하여 게임을 유리한쪽으로 유도하자!",
        price: 29.95,
      },
      {
        id: 8,
        name: "휴먼 체스보드",
        category: "Chess",
        description: "가족끼리 재밌는 게임을!",
        price: 75,
      },
      {
        id: 9,
        name: "블링 블링 킹",
        category: "Chess",
        description: "금과 다이아몬드를 노려라!",
        price: 1200,
      },
      {
        id: 10,
        name: "해리포터 체스",
        category: "Chess",
        description: "해리포터 주인공들과 함께 체스를!",
        price: 132,
      },
      {
        id: 11,
        name: "체스말",
        category: "Chess",
        description: "체스말이 없어진 당신을 위한 상품!",
        price: 30,
      },
      {
        id: 12,
        name: "체스판",
        category: "Chess",
        description: "체스판이 없어진 당신을 위한 상품!",
        price: 40,
      },
      {
        id: 13,
        name: "체스 탁자",
        category: "Chess",
        description: "프로페셔널한 체스를 두기위한 탁자!",
        price: 2000,
      },
      {
        id: 14,
        name: "체스 의자",
        category: "Chess",
        description: "프로페셔널한 체스를 두기위한 의자!",
        price: 75,
      },
      {
        id: 15,
        name: "체스로봇",
        category: "Chess",
        description: "혼자 연습이 불가능한 당신! , 체스로봇과 연습하세요!",
        price: 200000,
      },
      {
        id: 16,
        name: "체스과자",
        category: "Chess",
        description: "과자먹을때도 체스를 생각하며!",
        price: 30,
      },
      {
        id: 17,
        name: "치키차카초코초코체스!",
        category: "Chess",
        description: "아침 시리얼 대용으로도 체스!",
        price: 20,
      },
      {
        id: 18,
        name: "수영복",
        category: "Watersports",
        description: "수영할때도 패션을 잊지말자",
        price: 300,
      },
      {
        id: 19,
        name: "수영모",
        category: "Watersports",
        description: "100퍼센트 밀착감",
        price: 150,
      },
      {
        id: 20,
        name: "수영고글",
        category: "Watersports",
        description: "언제 어디서든 김이 안서리는 안경",
        price: 87,
      },
      {
        id: 21,
        name: "오리발",
        category: "Watersports",
        description: "수영할때 착용하면 부스터 효과!",
        price: 300,
      },
      {
        id: 22,
        name: "물갈퀴 장갑",
        category: "Watersports",
        description: "이것만 착용하면 당신도 펠프스!",
        price: 290,
      },
      {
        id: 23,
        name: "핸드폰 방수 주머니",
        category: "Watersports",
        description:
          "수영할때도 이것만 있으면 핸드폰을 들고 물안에 들어갈수 있다!",
        price: 30,
      },
      {
        id: 24,
        name: "고무튜브",
        category: "Watersports",
        description: "어린 아이도 안심!",
        price: 45,
      },
      {
        id: 25,
        name: "물놀이 세트",
        category: "Watersports",
        description: "어린아이들과 함께 놀아요!",
        price: 260,
      },
      {
        id: 26,
        name: "수영 전용 수건",
        category: "Watersports",
        description: "수영후 감기 조심하세요",
        price: 60,
      },
      {
        id: 27,
        name: "수구볼",
        category: "Watersports",
        description: "수구용 볼",
        price: 200,
      },
      {
        id: 28,
        name: "수구 네트",
        category: "Watersports",
        description: "수구용 네트",
        price: 100,
      },
      {
        id: 29,
        name: "축구화",
        category: "Soccer",
        description: "네이마르가 신던 축구화!",
        price: 400,
      },
      {
        id: 30,
        name: "축구 유니폼",
        category: "Soccer",
        description: "메시가 입었던 유니폼",
        price: 200,
      },
      {
        id: 31,
        name: "축구 스타킹",
        category: "Soccer",
        description: "손흥민이 직접 신었던 스타킹",
        price: 75,
      },
      {
        id: 32,
        name: "축구 무릎 보호대",
        category: "Soccer",
        description: "당신의 무릎을 소중히 하세요!",
        price: 90,
      },
      {
        id: 33,
        name: "골키퍼 장갑",
        category: "Soccer",
        description: "노이어 전용 장갑",
        price: 130,
      },
      {
        id: 34,
        name: "골대",
        category: "Soccer",
        description: "골대도 팝니다",
        price: 600,
      },
      {
        id: 35,
        name: "골대 그물망",
        category: "Soccer",
        description: "절대 뚫리지 않습니다",
        price: 300,
      },
      {
        id: 36,
        name: "잔디",
        category: "Soccer",
        description: "잉글랜드 프리미어리그 구장에서 직접 훔쳐왔습니다",
        price: 100000,
      },
      {
        id: 37,
        name: "심판",
        category: "Soccer",
        description: "제가 직접 경기 심판 봐드립니다",
        price: 1000,
      },
      {
        id: 38,
        name: "옐로카드",
        category: "Soccer",
        description: "심판을 처음하는 당신을 위한 아이템",
        price: 20,
      },
      {
        id: 39,
        name: "레드카드",
        category: "Soccer",
        description: "심판을 처음하는 당신을 위한 아이템",
        price: 20,
      },
      {
        id: 40,
        name: "심판깃발",
        category: "Soccer",
        description: "심판을 처음하는 당신을 위한 아이템",
        price: 120,
      },
      {
        id: 41,
        name: "야구공",
        category: "baseball",
        description: "류현진 사인볼이 올수도?",
        price: 200,
      },
      {
        id: 42,
        name: "야구 방망이",
        category: "baseball",
        description: "내일은 홈런볼",
        price: 500,
      },
      {
        id: 43,
        name: "포수글러브",
        category: "baseball",
        description: "투수공을 받아도 아프지 않다",
        price: 600,
      },
      {
        id: 44,
        name: "포수마스크",
        category: "baseball",
        description: "절대 부러질 염려 없는 안심100퍼센트",
        price: 50,
      },
      {
        id: 45,
        name: "야구유니폼",
        category: "baseball",
        description: "팀은 곧 하나다! 전원 같은걸로 맞추자",
        price: 80,
      },
      {
        id: 46,
        name: "야구 그라운드 선긋는 기계",
        category: "baseball",
        description: "하얀 분말이 잘나온다",
        price: 2050,
      },
      {
        id: 47,
        name: "배팅기계",
        category: "baseball",
        description: "직접 설치까지 해드리는 옵션 !",
        price: 30000,
      },
    ],
    orders: [],
  };
};
